name: WaterSplat-SLAM
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - tqdm
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  - pytorch-cuda=11.8
  - pip:
    - submodules/simple-knn
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL==3.1.9
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - openai-clip
    - torchcodec==0.1 # Optionally install torchcodec for faster mp4 loading
