inherit: "config/base.yaml"

use_calib: True
dataset:
  type: colmap
  subsample: 1
  img_downsample: 1
  image_subdir: Images_wb
  sparse_dir: sparse/0
  center_principle_point: True

tracking:
  match_frac_thresh: 0.3
  min_match_frac: 0.000

training:
  use_kf_BA: False
  kf_overlap: 0.6
  track_water_mask: False
  new_mapping_iter: 50
  normal_mapping_iters: 20
  C_conf: 0.5

color_refine:
  max_gaussian_points: 300000
  sh_max: 0
  config_sh_degree_interval: 1000
  clip_thresh: 0.01
  color_refinement_iters: 400

save_results: True
output:
  base_dir: "outputs/RedSea"
